### ISSUE TITLE
After frame artifacts

### ISSUE THREAD

**Issue by isbagricevich** [AvaloniaUI/Avalonia.GIF#17]
I am getting artifacts on the image in the demo. Tail of previous frames. Can I do something about it?
![image](https://user-images.githubusercontent.com/44448509/185624115-16ca6360-12e8-4d6a-af4c-05409115c165.png)
![image](https://user-images.githubusercontent.com/44448509/185624625-987b1e0f-672a-497d-9b7d-39142e9211cd.png)

**Comment by ZeroFantom** [comment]
I also have this problem. From what I see, there is a strict relationship between the application frames and the frames of the decoded gif image. This won't help you much, but I was able to control this behavior by slightly changing the code to the one below.
You can go further and catch broken frames (the consequences of the rigid dependence of frames in the application and gif images are artifacts).
Since we have information about each frame, we can try to reset the frames manually by noticing approximate fluctuations in the direction of pointing, thereby preventing the transition to the artifact state.
If you increase the dopTimeSpan value below to 450000~500000 ticks, you will see an almost perfect GIF image without artifacts and everything that follows, but the frame rendering speed will decrease by more than half.
** This cannot be considered a solution, it is only a temporary support.**
File: Gif Instance
Range: 58~67 lines
_I hope it was useful to you!_
![image](https://user-images.githubusercontent.com/34765874/202570876-e43ac497-48fc-4682-9268-9c13f001363b.png)
