### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by wberdowski** [AvaloniaUI/Avalonia.GIF#7]
Hello. I'm using your library in my Avalonia project and I stumbled upon an optimization problem. I need to display many gifs from the same file. Displaying around 10-20 gifs is fine, but when i try 50+, my CPU usage rises tremendously. Do you have any advice on how to overcome this problem?

**Comment by wberdowski** [comment]
bump

**Comment by jmacato** [comment]
@wberdowski sorry but GIF is quite flawed as a codec that I needed to balance between CPU usage and memory caching.. GIF websites currently cheats by just displaying the "GIF"s as MPEG video and that is highly optimized by today's CPUs.. there's nothing much i can do but to wait until we can get GPU-backed RenderTargetBitmaps so that we dont have to use too much CPU wehn transferring textures from RAM to the GPU memory. That will come soon on the next release of Avalonia i hope
